### ISSUE TITLE
camkes-arm-vm project is outdated, should be merged

### ISSUE THREAD

**Issue by lsf37** [seL4/docs#119]
The Arm VMs have been merged into other repos and the current doc site description is completely outdated, pointing to an archived repo.

It's not clear to me what exactly should replace it or how the description on the docsite should be merged, but it affects the following projects:

- https://docs.sel4.systems/projects/camkes-arm-vm/
- https://docs.sel4.systems/projects/camkes-vm/
- https://docs.sel4.systems/projects/virtualization/

**Comment by lsf37** [comment]
@nomadeel or @kent-mcleod could you help with this one?

**Comment by axel-h** [comment]
loosely related to https://github.com/seL4/docs/issues/119 that improves VM/CAmkESARMVM.md

**Comment by kent-mcleod** [comment]
camkes-arm-vm was merged into camkes-vm. So it may be good enough if this is done to the docs too.

**Comment by kent-mcleod** [comment]
https://github.com/seL4/docs/pull/140
