### ISSUE TITLE
Out of date/old status page

### ISSUE THREAD

**Issue by Ivan-Velickovic** [seL4/docs#125]
I stumbled upon https://docs.sel4.systems/Status through Google. I haven't been able to find this page any other way. Doesn't seem to be in this repository anywhere. The page itself looks pretty outdated and was probably left over in the process of moving stuff around or something like that.

I'd try remove it myself but I don't know how to and most likely don't have access to do so.

**Comment by lsf37** [comment]
I'll have a look -- it was removed from the repo, but seems to have stuck around on the server.

**Comment by lsf37** [comment]
Now deleted. Thanks for point it out.
