### ISSUE TITLE
Document support of Avnet MaaXBoard Board (i.MX8MQ) 

### ISSUE THREAD

**Issue by axel-h** [seL4/docs#142]
Follow-up from https://github.com/seL4/seL4/pull/829

Document Avnet MaaXBoard Board support and maintainer. Or list this as unmaintained and mention at least that a PR/branch exists with the changes.

**Comment by axel-h** [comment]
Work ongoing with https://github.com/seL4/docs/issues/142

**Comment by Ivan-Velickovic** [comment]
#145 has now been merged so this can be closed.
