### ISSUE TITLE
FAQ: immutable OS

### ISSUE THREAD

**Issue by leorosen** [seL4/docs#150]
Can Sel4 be used to build an immutable system?

**Comment by axel-h** [comment]
Yes, and with the CapDL loader and CAmkES there are already tools to create static system. That might be a starting point to evaluate your use case further.

**Comment by kent-mcleod** [comment]
[Link to CAmkES project page](https://docs.sel4.systems/projects/camkes/)

**Comment by Ivan-Velickovic** [comment]
There's also the seL4 Core Platform, https://github.com/BreakawayConsulting/sel4cp.
