### ISSUE TITLE
Make supported platforms page more consistent

### ISSUE THREAD

**Issue by Ivan-Velickovic** [seL4/docs#179]
It's not clear to me whether the page that lists supported platforms (https://docs.sel4.systems/Hardware/) is just for supported hardware or all platforms supported by seL4. E.g on RISC-V the Spike is listed but it's a purely simulated platform (to my knowledge). The page is also not named consistently, the URL is "Hardware", the title is "Supported Platforms" and the navigation bar has it listed as "Supported Hardware"

**Comment by lsf37** [comment]
A bit more consistency would definitely be nice. I think we should include simulation targets, but probably mark them as such.

**Comment by Ivan-Velickovic** [comment]
This was done in https://github.com/seL4/docs/pull/214, the URL is still "Hardware" though. @lsf37 do we want to bother with renaming the URL or should we just close this?

**Comment by lsf37** [comment]
Given that we're thinking about a more fundamental redesign of the website, let's just close this one for now.
