### ISSUE TITLE
displayed page modification date incorrect 

### ISSUE THREAD

**Issue by lsf37** [seL4/docs#196]
The footer shows site modification and page modification dates, but it looks like they are always the same and might always just be when the site got last generated.

**Comment by kent-mcleod** [comment]
The timestamp is extracted from the git history: https://github.com/seL4/docs/blob/master/Makefile#L33

Looks like the github action for checking out is only doing depth 1 which results in all pages being last modified in the same commit:

```
    # Number of commits to fetch. 0 indicates all history for all branches and tags.
    # Default: 1
    fetch-depth: ''
```

**Comment by lsf37** [comment]
Thanks for tracking that down, I'll change it to full depth.
