### ISSUE TITLE
RPi4 Docs missing `fixup4.dat`

### ISSUE THREAD

**Issue by wucke13** [seL4/docs#241]
According to the [RaspberryPI documentation](https://www.raspberrypi.com/documentation/computers/configuration.html#fixup-dat) the `fixup*.dat` are matched pairs together with the `start*.elf` files. Therefore I conclude that if `start4.elf` is required (which is explicitly mentioned in the seL4 docs on the RPi4), then the corresponding `fixup4.dat` is also required. This should be documented in the table marked below:

https://github.com/seL4/docs/blob/796c55286291aeede9785638bff03703e387752d/Hardware/Rpi4.md?plain=1#L41-L50

**Comment by Ivan-Velickovic** [comment]
Thanks for making an issue about this, fixed in https://github.com/seL4/docs/pull/242.

**Comment by wucke13** [comment]
@Ivan-Velickovic Thank you for the super quick fix!
