### ISSUE TITLE
Version of cmake broke the pipe on ubuntu1804

### ISSUE THREAD

**Issue by tecty** [seL4/docs#51]
I have tried the build on ubuntu, the version can be install on it is cmake 3.10.x. And another ppa is broken too (unable to find IP). Snap will fix this problem by:

```bash 
snap install cmake  --classic 
```

**Comment by tecty** [comment]
There's more things broke, things required by interrupts tutorial are:
```bash
pip3 install libarchive
sudo apt install -y libarchive-dev cpio
```

**Comment by lsf37** [comment]
Hey @tecty I'm guessing you're referring to things missing in the Ubuntu section on https://docs.sel4.systems/projects/buildsystem/host-dependencies.html to get the Interrupts tutorial running -- is the info there still wrong or do the steps now work?

**Comment by tecty** [comment]
As soon as the ubuntu 2004 comes out, I switch to new os. So it doesn't matter for now.
