### ISSUE TITLE
How large is seL4?

### ISSUE THREAD

**Issue by sorear** [seL4/docs#59]
[Heiser and Elphinstone 2016](https://ts.data61.csiro.au/publications/nicta_full_text/8988.pdf#page=5):

> The kernel compiles into about 9 k ARM instructions."

[The current FAQ](https://docs.sel4.systems/projects/sel4/frequently-asked-questions.html):

> In terms of executable code size, on the 64-bit RISC-V architecture, the single-core kernel compiles into about 138 KiB. Its RAM size is about 162 KiB, which includes code, static data and the stack. Meta-data for usermode processes, incl. address spaces (page tables), thread-control blocks, capability storage etc, will add to this. (But note that in seL4’s memory-management model, such dynamic memory must be supplied to the kernel by usermode code.)

138 KiB is about 47 K RISC-V instructions, depending on the effectiveness of compression.  Is RISC-V that poorly suited (no bitfield instructions, etc) to seL4 or if not what changed since 2016?  So I built the spike/riscv64 kernel.

The default build following [the Docker quickstart instructions](https://docs.sel4.systems/projects/dockerfiles/) with minimal changes for RISC-V (use the `user_sel4-riscv` Makefile target, change `stack` to `sudo` in the Makefile because the riscv image does not have stack, and configure with `-DPLATFORM=spike`) produces a 910KiB `kernel.elf`, unstripped.  The `size` command reports 141KiB of text, very close to the reported number, increasing to 165 KiB including bss and data; I think this is where the numbers came from.

Disassembling and counting gives 20442 instructions occupying 60144 bytes - still a significant apparent regression, but in significant disagreement with the `size` output.  The size output matches the sum of the length of `.boot`, `.text`, `.srodata`, and `.rodata`; `.boot` in its entirety is flagged in a text section, and because of the placement of the alignment, the full 64KiB alignment of `.text` is counted against the size of `.boot`.

Adjusting the linker script to separate .boot.text and .boot.data and moving the alignment outside of either results in a `size` measurement of 90 KiB "text" (still includes rodata) and 115 KiB total.

The 64KiB alignment might be a fossil of ARM's large frames; reducing it to 4KiB shrinks the kernel binary by 48 KiB and does not appear to affect sel4test (this does not affect runtime memory use since it's all returned as an untyped).

The bigger problem is that _this is a debug build_.  (For a competitor, this is a listed "benchmarking crime").  The rodata is mostly string error messages.

A `-DRELEASE=TRUE` build has 14683 instructions (3614 in .boot.text, 11069 in .text) occupying 40952 (10146, 30806) bytes.  
The total size of the load image as reported by `objdump -p` is 46 KiB text and initialized data, 69 KiB including bss (of which 12 KiB is returned as boot memory)  This is within a plausible ballpark of the 2016 numbers.

**Comment by xurtis** [comment]
When reporting the sizes of source or binaries, we are generally referring to the verified configurations (under the [`configs` directory in the seL4 kernel repository](https://github.com/seL4/seL4/tree/master/configs)).

With GCC 8, it seems that the `.text` region for the `RISCV64` configuration is just shy of 31KiB whereas the `ARM` (aarch32 w/o hypervisor support) is almost 64KiB.

The memory consumed by the `.boot` regions in the configurations we supply is reclaimed after boot and can be re-used by the user-level so the impact of their size in-memory is usually minimal (although can make it difficult to store the boot image in more constrained situations). The alignment of 64KiB for RISC-V does seem unnecessary but it may relate to the allocation of untypeds from the reclaimed memory.

**Comment by kent-mcleod** [comment]
If you build a kernel following the instructions here: https://docs.sel4.systems/projects/sel4/verified-configurations.html#examining-and-building-verified-configurations you get:
```
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .boot             PROGBITS         ffffffff84000000  00001000
       0000000000010000  0000000000000000 WAX       0     0     8
  [ 2] .text             PROGBITS         ffffffff84010000  00011000
       0000000000007b32  0000000000000000  AX       0     0     2
  [ 3] .srodata          PROGBITS         ffffffff84017b38  00018b38
       0000000000000008  0000000000000000   A       0     0     8
  [ 4] .rodata           PROGBITS         ffffffff84017b40  00018b40
       0000000000000ac8  0000000000000000   A       0     0     8
  [ 5] ._idle_thread     PROGBITS         ffffffff84018800  00019800
       0000000000000400  0000000000000000  WA       0     0     512
  [ 6] .bss              NOBITS           ffffffff84018c00  00019c00
       0000000000015ea8  0000000000000000  WA       0     0     4096
```
which is about 31KiB text, 122KiB total not counting the .boot section.  If you count boot without the 64KiB alignment then its 134KiB.  The verification configuration should be very similar to what sel4test builds with if you specify -DRELEASE=True and -DVERIFICATION=True and there shouldn't be a large difference between changing -DVERIFICATION values.  I believe the 138KiB number quoted in the FAQ likely just took the sections as reported by objdump and 138KiB includes all program sections.  Since that number was calculated for the FAQ, there have been some modifications to the init code that changed the way that some static kernel objects were allocated (such as the idle thread object) so that they were statically declared in the .bss instead of being dynamically allocated during boot, but there shouldn't have been any significant changes in total number of instructions from in that time.
