### ISSUE TITLE
Barrier to entry

### ISSUE THREAD

**Issue by stefangotz** [seL4/docs#75]
I noticed that the entry level documentation pages contain several dead links and the link to the latest manual leads to a manual for v11, not v12 which appears to be the latest release

**Comment by oliver-wm** [comment]
Thanks, I'll look into it.

**Comment by oliver-wm** [comment]
Can you please specify which links you are talking about?

**Comment by stefangotz** [comment]
Hello Oliver,

A link checker, such as https://www.site24x7.com/link-checker.html, finds a few broken links on the following URLs:

- https://docs.sel4.systems/projects/sel4/documentation.html
- https://docs.sel4.systems/GettingStarted.html

Hope that helps!

Kind regards,
       Stefan

**Comment by oliver-wm** [comment]
Cheers!

**Comment by stefangotz** [comment]
Thank you, Oliver! :)
